version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn pack --filename package.tgz
      - store_artifacts:
          path: package.tgz
          destination: dist
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/project/.npmrc
      # TODO: change this to "--access restricted" when adapting for private
      # npm package use
      # - run: npm publish package.tgz --access public
      - run: yarn auto shipit

workflows:
  version: 2

  build-test-and-publish:
    jobs:
      - deploy
      # - deploy:
      #     context: design-system
          #filters:
          #  branches:
          #    only: master
