version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn auto shipit

workflows:
  version: 2

  build-test-and-publish:
    jobs:
      - deploy:
      # - deploy:
      #     context: design-system
          filters:
           branches:
             only: master
